FROM node:12.16.1

WORKDIR /slotsevo_web/
COPY web/ .

RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm install || npm install
RUN npm run build

FROM nginx:alpine
LABEL MAINTAINER="0xl1352807232@gmail.com"

COPY .docker-compose/nginx/conf.d/my.conf /etc/nginx/conf.d/my.conf
COPY --from=0 /slotsevo_web/dist /usr/share/nginx/html
CMD ls -al /usr/share/nginx/html
