captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
jwt:
  signing-key: qmPlus
  expires-time: 604800
  buffer-time: 86400
local:
  path: uploads/file
mysql:
  path: www.xiaoliang007.asia:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: slotsevo_admin
  username: admin
  password: slotsevoadmin123456
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: false
  log-zap: ""
redis:
  db: 0
  addr: www.xiaoliang007.asia:6379
  password: ""
rpc:
  host: http://192.168.2.34
  port: "7003"
  timeout: 1
  retryCount: 3
  retryWaitTime: 5
  retryMAxWaitTime: 20
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
timer:
  start: true
  spec: '@daily'
  detail:
  - taskName: clear_log
    keepDays: 5
zap:
  level: info
  format: console
  director: log
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: false
